### PR TITLE
Improve (and fix) reader of tags for binaries.

### LINKED ISSUE #14: [BUG] Invalid version string on rr get-binary
@rustatian 
I'm getting an error when trying to do `rr get-binary`.
The version string referenced is the latest pre-release in the repo.

I tried this code:

```
/var/www/vendor/bin/rr get-binary
```

I expected to see this happen: a normal download of the binary

Instead, this happened: 
```
spiral/roadrunner#25 1.324 
spiral/roadrunner#25 1.324  Environment:
spiral/roadrunner#25 1.324    - Version:          2.*
spiral/roadrunner#25 1.326    - Stability:        stable
spiral/roadrunner#25 1.329    - Operating System: linux
spiral/roadrunner#25 1.329    - Architecture:     amd64
spiral/roadrunner#25 1.329 
spiral/roadrunner#25 1.993 
spiral/roadrunner#25 2.017 In VersionParser.php line 185:
spiral/roadrunner#25 2.018                                                              
spiral/roadrunner#25 2.018   Invalid version string "Plugins separate repo experiment"  
spiral/roadrunner#25 2.018                                                              
spiral/roadrunner#25 2.018 
spiral/roadrunner#25 2.018 get-binary [-o|--os [OS]] [-a|--arch [ARCH]] [-f|--filter [FILTER]] [-l|--location [LOCATION]] [-s|--stability [STABILITY]]
spiral/roadrunner#25 2.018 
```

The version of RR used: 2.*
  
My `.rr.yaml` configuration is: can supply if needed

### PR DESCRIPTION
**Pull request by SerafimArts**

### CODE REVIEW

**Comment by driesvints** [comment]
Heya, we "think" this PR might have broken Laravel Octane installations. For some reason we now get 4 digits for the roadrunner binary version number: https://github.com/laravel/octane/issues/387

**Comment by SerafimArts** [comment]
@driesvints I cannot reproduce the problem =(

**Comment by driesvints** [comment]
No worries @SerafimArts. I really wonder what's going on...

**Comment by SerafimArts** [comment]
@driesvints I can guess that the problem (may be) is somewhere in the composer's version normalizer (https://github.com/spiral/roadrunner-cli/blob/master/composer.json#L26) and some version of this package returns 4 digits instead of 3x.

**Comment by SerafimArts** [comment]
Problem found and resolved https://github.com/spiral/roadrunner-cli/releases/tag/v2.0.9

**Comment by driesvints** [comment]
Thanks @SerafimArts!

**Pull request merged**
